wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1641467205
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.7.11
      5: 0.12.9
      8:
      - 5
learning_rate:
  desc: null
  value: 0.0453288077829833
optimizer:
  desc: null
  value: sgd
